language: node_js
node_js:
  - 'stable'
branches:
  only:
    - 'master'
cache:
  directories:
    - node_modules
install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - npm test
